GetListUsers
srp-internships/MRA.Identity pull request #38
Opened 2024-02-28 06:13 UTC by Muhammadislom99

2024-02-28 06:16 UTC, Firuz2006 approved these changes

2024-02-28 10:27 UTC, komdil requested changes

2024-02-28 10:27 UTC, komdil commented on src/MRA.Identity.Application/Features/Users/Query/GetListUsersQueryHandler.cs
> +            users = users.Where(u => (u.FirstName + " " + u.LastName).Contains(request.FullName.Trim()));
add tests

2024-03-01 08:49 UTC, Firuz2006 approved these changes

2024-03-01 08:57 UTC, komdil approved these changes

2024-03-01 08:58 UTC, merged