GetUser-and-GetProfile-By-ApplicatonId
srp-internships/MRA.Identity pull request #67
Opened 2024-04-15 13:54 UTC by Muhammadislom99

2024-04-15 14:05 UTC, Firuz2006 requested changes
Security problems! I think we need to create another controller for admins and also get ApplicantId or Applicant username from token.

2024-04-15 14:05 UTC, Firuz2006 commented on src/MRA.Identity.Api/Controllers/ProfileController.cs
>      public async Task<IActionResult> GetProfileByUserName([FromQuery] string userName = null)
Any applicant can access to the another applicant profile if he knows id?

2024-04-15 15:20 UTC, SidiqovAbbos approved these changes

2024-04-18 10:50 UTC, Firuz2006 approved these changes

2024-04-19 11:47 UTC, merged